export declare const BALANCED_PHASE_1 = "\n**PHASE 1: ARCHITECTURAL ANCHORING**\n\nThe following elements are FIXED and must not change:\n- Wall planes, floor plane, and ceiling plane\n- Window and door frames, their exact positions and sizes\n- Camera angle, focal length, and perspective vanishing points\n- Room spatial proportions and overall depth\n\nThe following elements are NOT fixed \u2014 they will be fully replaced in Phase 2:\n- All furniture, decor, rugs, accessories, and staging items (treat as absent)\n- Surface finishes on walls, floors, and ceiling (will be restyled)\n- Lighting fixtures and lamps (will be replaced)\n\nTreat the image as an architectural shell with locked geometry. Do not carry over\nany existing furnishing, sparseness, or decor into Phase 2. A complete interior\ntransformation follows.\n";
export { INFLUENCE_PRIORITIZE_PRESET_STYLE, INFLUENCE_PRIORITIZE_MOOD_BOARD, INFLUENCE_BALANCE_STYLE_AND_MOOD_BOARD, INFLUENCE_PRESET_STYLE_ONLY, INSTRUCTION_INTEGRATE_FURNITURE, DEFAULT_USER_REQUEST, } from '../improved/visualization.constants.js';
export declare const BALANCED_PHASE_2_HEADER = "\n**PHASE 2: STYLE TRANSFORMATION**\n- Room Type: {{ROOM_TYPE}}\n- Task: Transform the room into the {{STYLE_NAME}} aesthetic.\n- Output Goal: A photorealistic, fully-furnished result of the SAME room.\n- User request: \"{{USER_REQUEST}}\"\n";
export declare const FURNISHING_MANDATE = "\n**FURNISHING MANDATE \u2014 EXECUTE BEFORE ALL OTHER INSTRUCTIONS:**\n- The source image is an architectural shell. All furniture has been cleared.\n- You MUST introduce a complete, professionally staged furniture layout for the {{ROOM_TYPE}}.\n- Furniture density target: a professionally staged, realistic residential interior with a complete furniture layout.\n- Do NOT leave any part of the room empty, sparse, or understaged.\n- Do NOT carry any existing furniture, sparseness, or staging from the source image into the output.\n- Furnishing must clearly reflect the {{STYLE_NAME}} style \u2014 generic or neutral staging is not acceptable.\n";
export declare const STYLE_PRIORITY = "\n**STYLE PRIORITY:**\n- Ensure the design clearly reflects the defining characteristics of the selected style.\n- Use the provided materials, colors, and finishes to create a distinctive and recognizable aesthetic.\n- Avoid overly neutral or generic interpretations.\n";
export declare const REALISM_CONSTRAINT = "\n**REALISM CONSTRAINT:**\n- The room must feel like a real, livable residential interior, not a conceptual render or cinematic scene.\n- Avoid dark, moody, or theatrically dim lighting. Warm, well-lit residential lighting is preferred and does not count as dramatic.\n- Materials, lighting, and furniture should feel natural, vibrant, and appropriate for everyday living.\n- The result should resemble a professionally staged home renovation visualization, not a stylized design showcase.\n";
export declare const DESIGN_RULES = "\n**DESIGN RULES:**\n\n1. **Architectural Priority:**\n   - Furniture adapts to the room \u2014 not the reverse.\n   - Do not alter walls, windows, doors, or architectural openings to fit furniture.\n   - Apply all materials as surface treatments, not structural additions.\n   - Do not introduce new walls, partitions, or dividers.\n\n2. **Material Zoning:**\n   - Apply materials selectively and realistically.\n   - Balance dominant materials with quieter secondary surfaces \u2014 do not repeat one material on every surface.\n\n3. **Lighting:**\n   - Use warm, natural daylight as the primary light source \u2014 target a warm white to golden ambient color temperature.\n   - Maintain bright, warm visibility that makes materials look rich and saturated, not washed out or desaturated.\n   - Avoid cool, overcast, or blue-gray daylight renderings \u2014 the room should feel sun-warmed, not cloud-filtered.\n   - Avoid dark, moody, theatrical, or cinematic lighting unless explicitly requested by the user.\n   - Shadows should be soft, warm, and realistic \u2014 directional but not harsh.\n";
export declare const RENOVATION_FEASIBILITY_RULES = "\n**RENOVATION FEASIBILITY RULES:**\n- Apply materials in ways consistent with real-world construction.\n- Do not apply heavy materials (such as stone or brick) to thin, detailed, or ornamental architectural features.\n- Large-scale materials must respect existing wall planes and proportions.\n- If a material conflicts with geometry, adapt the material \u2014 do not distort the structure.\n";
export declare const LIGHTING_NORMALIZATION = "\n**LIGHTING NORMALIZATION:**\n- Regardless of style, keep the final image warm, well-lit, and residential in color temperature.\n- Avoid cool or overcast ambient light \u2014 use warm white to golden daylight as the base tone.\n- Do not let style-specific lighting terms make the room significantly darker OR cooler than the source image.\n- If the style suggests darker or rawer materials, balance them with warm ambient daylight to preserve material vibrancy.\n- Rendered materials must appear rich and chromatic \u2014 walnut should look warm brown, not gray-brown; olive should read green, not khaki.\n";
export declare const BALANCED_PROTOCOL_RIGID_BASE = "\n**STRUCTURAL PROTOCOL:**\n- Preserve all walls, architectural openings, and the original spatial layout.\n- No structural reinterpretation permitted.\n";
export declare const BALANCED_PROTOCOL_RIGID_APERTURE_LOCK = "\n**STRUCTURAL PROTOCOL:**\n- Preserve all walls, architectural openings, and the original spatial layout.\n- Protect windows, glass areas, and uninterrupted wall spans.\n- Do not insert partitions, dividers, or structural separators.\n- Where a requested material conflicts with decorative trim, respect core wall geometry and apply the material as a flat surface treatment.\n";
export declare const BALANCED_PROTOCOL_SURFACE_ONLY_TRANSFORM = "\n**STRUCTURAL PROTOCOL:**\n- Preserve all architectural edges, junctions, and transitions.\n- Maintain the 3D depth and complexity of the original room structure.\n- Finishes and visual surfaces may be simplified, but do not flatten or erase existing architectural boundaries.\n";
//# sourceMappingURL=visualization.constants.d.ts.map