export { INFLUENCE_PRIORITIZE_PRESET_STYLE, INFLUENCE_PRIORITIZE_MOOD_BOARD, INFLUENCE_BALANCE_STYLE_AND_MOOD_BOARD, INFLUENCE_PRESET_STYLE_ONLY, INSTRUCTION_INTEGRATE_FURNITURE, DEFAULT_USER_REQUEST, } from '../improved/visualization.constants.js';
export declare const BALANCED_V2_1_PHASE_1 = "\n**PHASE 1: ARCHITECTURAL ANCHORING**\n\nThe following elements are FIXED and must not change:\n- Wall planes, floor plane, and ceiling plane\n- Window and door frames, their exact positions and sizes\n- Camera angle, focal length, and perspective vanishing points\n- Room spatial proportions and overall depth\n\nTreat the input image as a real room undergoing renovation \u2014 not an empty architectural shell.\n- Modify, replace, or upgrade surface finishes, furniture, and decor as needed for the selected style.\n- Preserve the underlying spatial logic, layout, lighting behavior, and realism of the original room.\n- The result should feel like a before-and-after renovation of the same physical space, not a rebuilt scene.\n";
export declare const BALANCED_V2_1_PHASE_2_HEADER = "\n**PHASE 2: STYLE TRANSFORMATION**\n- Room Type: {{ROOM_TYPE}}\n- Task: Transform the room into the {{STYLE_NAME}} aesthetic.\n- Output Goal: A photorealistic, fully-furnished renovation result of the SAME room.\n- User request: \"{{USER_REQUEST}}\"\n";
export declare const RENOVATION_CONTINUITY = "\n**RENOVATION CONTINUITY:**\n- The output must feel like a real renovation of the input room, not a reimagined or rebuilt scene.\n- Maintain plausible furniture placement relative to walls, windows, circulation paths, and focal points.\n- Avoid dramatic re-layouts that ignore the original spatial logic.\n- The result should feel like a before-and-after transformation of the same room.\n";
export declare const FURNISHING_STRATEGY = "\n**FURNISHING STRATEGY:**\n- Furnish the room in a complete but realistic way for the selected room type and style.\n- You may reuse, adapt, or replace furniture as needed to match the target style.\n- If the source room is empty, introduce a plausible furniture layout appropriate for the style.\n- Do not leave the room empty unless explicitly requested.\n- Do not over-stage the room beyond what is realistic for a lived-in, professionally designed interior.\n- Furnishing must reflect realistic use of the space (sleeping, storage, circulation).\n- Avoid unnecessary or decorative-only objects that do not support the room's function.\n";
export declare const OBJECT_PLACEMENT_LOGIC = "\n**OBJECT PLACEMENT LOGIC:**\n- Every furniture or decor item must have a clear functional or spatial justification.\n- Do NOT place objects solely to fill empty wall space or balance composition.\n- Avoid isolated or unsupported items (e.g., standalone mirrors, chairs, or decor with no relationship to nearby furniture).\n- Vertical elements (mirrors, art, shelving) must be anchored to a logical surface:\n  - above a dresser or console\n  - aligned with a bed or seating area\n  - integrated into a cohesive wall composition\n- Floor objects must respect circulation and not block natural movement paths.\n- If a placement feels arbitrary or unsupported, omit the object instead of forcing it into the scene.\n- Prefer omission over arbitrary placement.\n";
export declare const STYLE_PRIORITY = "\n**STYLE PRIORITY:**\n- Ensure the design clearly reflects the defining characteristics of the selected style.\n- Use the provided materials, colors, and finishes to create a distinctive and recognizable aesthetic.\n- Avoid overly neutral or generic interpretations.\n- Style must be expressed through materials, color palette, and furniture selection \u2014 not through excessive decor or arbitrary object placement.\n";
export declare const REALISM_CONSTRAINT = "\n**REALISM CONSTRAINT:**\n- The room must feel like a real, livable residential interior, not a conceptual render or cinematic scene.\n- Avoid dark, moody, or theatrically dim lighting. Warm, well-lit residential lighting is preferred and does not count as dramatic.\n- Materials, lighting, and furniture should feel natural, vibrant, and appropriate for everyday living.\n- The result should resemble a professionally staged home renovation visualization, not a stylized design showcase.\n";
export declare const DESIGN_RULES_V2_1 = "\n**DESIGN RULES:**\n\n1. **Architectural Priority:**\n   - Furniture adapts to the room \u2014 not the reverse.\n   - Do not alter walls, windows, doors, or architectural openings to fit furniture.\n   - Apply all materials as surface treatments, not structural additions.\n   - Do not introduce new walls, partitions, or dividers.\n\n2. **Material Zoning:**\n   - Apply materials selectively and realistically.\n   - Balance dominant materials with quieter secondary surfaces \u2014 do not repeat one material on every surface.\n\n3. **Lighting:**\n   - Maintain the light directionality and spatial character of the original image.\n   - Preserve material readability \u2014 surfaces should remain clearly visible and color-accurate.\n   - Shadows should be soft and realistic, consistent with the original image's ambient conditions.\n";
export declare const RENOVATION_FEASIBILITY_RULES = "\n**RENOVATION FEASIBILITY RULES:**\n- Apply materials in ways consistent with real-world construction.\n- Do not apply heavy materials (such as stone or brick) to thin, detailed, or ornamental architectural features.\n- Large-scale materials must respect existing wall planes and proportions.\n- If a material conflicts with geometry, adapt the material \u2014 do not distort the structure.\n";
export declare const LIGHTING_PRESERVATION_AND_NORMALIZATION = "\n**LIGHTING PRESERVATION AND NORMALIZATION:**\n- Preserve the brightness level of the original image.\n- Do not make the scene darker than the input unless explicitly requested.\n- Maintain the same daylight direction and realistic daylight intensity.\n- Use bright, natural, residential lighting with warm-to-neutral white color temperature.\n- Avoid cinematic lighting, heavy contrast, moody shadows, and overcast gray tones.\n- Materials must remain well-lit, color-accurate, and visually readable.\n- The final image should feel like it was photographed in natural daylight, not dramatically lit for mood.\n";
export declare const BALANCED_V2_1_PROTOCOL_RIGID_BASE = "\n**STRUCTURAL PROTOCOL:**\n- Preserve all walls, architectural openings, and the original spatial layout.\n- No structural reinterpretation permitted.\n";
export declare const BALANCED_V2_1_PROTOCOL_RIGID_APERTURE_LOCK = "\n**STRUCTURAL PROTOCOL:**\n- Preserve all walls, architectural openings, and the original spatial layout.\n- Protect windows, glass areas, and uninterrupted wall spans.\n- Do not insert partitions, dividers, or structural separators.\n- Where a requested material conflicts with decorative trim, respect core wall geometry and apply the material as a flat surface treatment.\n";
export declare const BALANCED_V2_1_PROTOCOL_SURFACE_ONLY_TRANSFORM = "\n**STRUCTURAL PROTOCOL:**\n- Preserve all architectural edges, junctions, and transitions.\n- Maintain the 3D depth and complexity of the original room structure.\n- Finishes and visual surfaces may be simplified, but do not flatten or erase existing architectural boundaries.\n";
//# sourceMappingURL=visualization.constants.d.ts.map